### ISSUE TITLE
The block caret under Vim mode now blinks instead

### ISSUE THREAD

**Issue by x-ji** [stefansundin/atom-stop-cursor-blinking#1]
The normal cursor stopped blinking, but under `vim-mode-plus`, the block caret starts blinking instead.

**Comment by x-ji** [comment]
Seems that this method works https://discuss.atom.io/t/how-to-stop-the-blinking-of-cursor/22790/12

**Comment by stefansundin** [comment]
Sorry, I totally missed the github emails. I managed to fix it, and just released v1.0.1.

**Comment by stefansundin** [comment]
Forgot to mention, this is the reason I can't use `atom-text-editor .cursor { opacity: 1 !important }`.. even when a field is not focused, the cursor is visible.

![screen shot 2018-05-02 at 14 31 22](https://user-images.githubusercontent.com/1991151/39731703-fb58656a-521d-11e8-8034-7d03233bcfbf.png)
